group: travis_latest
sudo: false
language: node_js
node_js:
  - &latest_tested 9
  - 8
  - 7
  - 6

env:
  matrix:
    - MONGOOSE=5
    - MONGOOSE=4

services:
  - mongodb

cache:
  directories:
    - node_modules

before_install: node ./build/set-mongoose-version.js

before_cache: rm -rf ./node_modules/.cache

before_script:
  - npm run build
  - npm run tslint

script: npm test

after_success: cat ./coverage/lcov.info | coveralls