group: travis_latest
sudo: false
language: node_js

stages:
  - &lintStage Lint
  - &testStage Test

cached_stage: &cachedStage
  cache: &cache
    directories:
      - node_modules
  before_cache: rm -rf ./node_modules/.cache

test_stage_base: &testStageBase
  <<: *cachedStage
  stage: *testStage
  services:
    - mongodb
  before_install: node ./build/set-mongoose-version.js
  script:
    - npm test
    - npm run test:entry
    - mv ./node_modules/tslib ./node_modules/tslib.bak
    - npm run test:entry
    - mv ./node_modules/tslib.bak ./node_modules/tslib
  before_script: npm run build
  after_success: cat ./coverage/lcov.info | coveralls

jobs:
  include:
    - stage: *lintStage
      <<: *cachedStage
      before_install:
        - cp package.json package.json.bak
        - node ./build/filter-lint-depedencies.js
      before_script: mv package.json.bak package.json -f
      script: npm run tslint
      node_js: &latest_tested 9
    - <<: *testStageBase
      node_js: 9
      env:
        - MONGOOSE=5
    - <<: *testStageBase
      node_js: 9
      env:
        - MONGOOSE=4

    - <<: *testStageBase
      node_js: 8
      env:
        - MONGOOSE=5
    - <<: *testStageBase
      node_js: 8
      env:
        - MONGOOSE=4

    - <<: *testStageBase
      node_js: 6
      env:
        - MONGOOSE=5
    - <<: *testStageBase
      node_js: 6
      env:
        - MONGOOSE=4
