group: travis_latest
sudo: false
language: node_js
node_js:
  - &latest_tested 9
  - 8
  - 7
  - 6

services:
  - mongodb

cache:
  directories:
    - node_modules

before_cache: rm -rf ./node_modules/.cache

after_success: cat ./coverage/lcov.info | coveralls
before_script:
  - npm run build
  - npm run tslint

script: npm test