group: travis_latest
sudo: false
language: node_js

stages:
  - &testStage Test & Lint

test_stage_base: &testStageBase
  stage: *testStage
  services:
    - mongodb
  cache: &cache
    directories:
      - node_modules
  before_cache: rm -rf ./node_modules/.cache
  before_install: node ./build/set-mongoose-version.js
  script: npm test
  before_script: npm run build
  after_success: cat ./coverage/lcov.info | coveralls

jobs:
  include:
    - <<: *testStageBase
      node_js: &latest_tested 9
      env:
        - MONGOOSE=5
      script:
        - npm test
        - npm run tslint
    - <<: *testStageBase
      node_js: 9
      env:
        - MONGOOSE=4

    - <<: *testStageBase
      node_js: 8
      env:
        - MONGOOSE=5
    - <<: *testStageBase
      node_js: 8
      env:
        - MONGOOSE=4

    - <<: *testStageBase
      node_js: 6
      env:
        - MONGOOSE=5
    - <<: *testStageBase
      node_js: 6
      env:
        - MONGOOSE=4
