group: travis_latest
sudo: false
language: node_js

node_js:
  - stable
  - lts/carbon
  - lts/boron

env:
  matrix:
    - MONGOOSE=5
    - MONGOOSE=4

services:
  - mongodb

cache:
  yarn: true
  directories:
    - node_modules
before_cache: rm -rf node_modules/.bin/.cache

before_install:
  - npm install -g greenkeeper-lockfile yarn
  - greenkeeper-lockfile-update
  - node ./build/set-mongoose-version.js
install: yarn install --check-files
before_script: yarn run typecheck
script:
  - yarn run tslint
  - yarn test
after_success: cat ./coverage/lcov.info | coveralls
after_script: if [[ $GH_TOKEN ]]; then greenkeeper-lockfile-upload; fi;

stages:
  - Test
  - name: Release
    if: tag IS present

jobs:
  include:
    - stage: Release
      node_js: stable
      env:
        - MONGOOSE=5
      services: []
      before_install: true
      before_script: false
      script: node ./build/version-is-tampered-with.js --echo --exit
      after_success: true
      after_script: true
      before_deploy:
        - node ./build/set-badges-branch.js
        - yarn run build --sourceMap false
        - yarn run doctoc
      deploy:
        - provider: npm
          on:
            tags: true
          skip_cleanup: true
          email: a.molcanovas@gmail.com
          api_key:
            secure: "pTE7TQoDjwJaiSrLvDzryD/J6ZN+0u0pW/OysbbFp43i45oAm+7xGfDKggoeaaKIGoVrzA8A7u8G8L7UaU5xgIS2q19bAiXxewztuNQzM/8MQ/xDMP3OEetXUiN4ZzsOiE78OMCh+riFcnAoIsDMv7kg2/kj9EzK3YsWybwHTST2su0/xrDAd42SaEcJ14FT5o9nzfV86mpbScP1XZUBWx2BmLHcZHQrzKtayPE2E83MOSO9Z//KclxQTZWsHhgJDlMglZU83aoUpbbT/bSrlTVgsc1q2imlBNEYSBq08slQUlivjeweL49rWOFWXu/7QzlSPOUSxA59hIsiNV2uBic5z/4taRjTRYSs1skH78SrGv2yS24JcG9MrpORR0pc39Qj4am4XcTbp2CsZdxdLNshgoKM3Jn7ulsEePFvX/PhkeDe6pNaILvNsDU2fUV7pA0JG2GwEsSrBDPMfFicx4VH1ax8NnQlZSR1uQ2C8bzduc0YYwlIE85cfFd2+csZ3hpQkEDpOKSJANkA8O0qdJsg5/bKBvsB4SXb92FpxYq+xHbsCWASO7pvekBK7fhKJugv//xkSul2OYSGhYYWnNfLEkw9AdTOCzMX84e9+RxKEsYcfFz08Rsg/81rIR44fS8SDJ/hBgY1Mk4vkNKr8uf1m6I/GMd5NdPO1tNPY3M="
